<?php

/**
 * This is the model base class for the table "warehouse.products".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Products_exGiix".
 *
 * Columns in table "warehouse.products" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $proID
 * @property integer $catID
 * @property integer $supID
 * @property string $item
 * @property string $price
 * @property string $type
 * @property string $modelID
 * @property string $itemDesc
 * @property string $weight
 * @property string $createDate
 * @property string $modifiedDate
 *
 */
abstract class BaseProducts_exGiix extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'warehouse.products';
	}

	public static function representingColumn() {
		return 'item';
	}

	public function rules() {
		return array(
			array('catID, supID, item, price, type, modelID, itemDesc, weight, createDate, modifiedDate', 'required'),
			array('catID, supID', 'numerical', 'integerOnly'=>true),
			array('item', 'length', 'max'=>255),
			array('price', 'length', 'max'=>19),
			array('type, modelID', 'length', 'max'=>30),
			array('itemDesc', 'length', 'max'=>100),
			array('weight', 'length', 'max'=>20),
			array('proID, catID, supID, item, price, type, modelID, itemDesc, weight, createDate, modifiedDate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'proID' => Yii::t('app', 'Pro'),
			'catID' => Yii::t('app', 'Cat'),
			'supID' => Yii::t('app', 'Sup'),
			'item' => Yii::t('app', 'Item'),
			'price' => Yii::t('app', 'Price'),
			'type' => Yii::t('app', 'Type'),
			'modelID' => Yii::t('app', 'Model'),
			'itemDesc' => Yii::t('app', 'Item Desc'),
			'weight' => Yii::t('app', 'Weight'),
			'createDate' => Yii::t('app', 'Create Date'),
			'modifiedDate' => Yii::t('app', 'Modified Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('proID', $this->proID);
		$criteria->compare('catID', $this->catID);
		$criteria->compare('supID', $this->supID);
		$criteria->compare('item', $this->item, true);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('modelID', $this->modelID, true);
		$criteria->compare('itemDesc', $this->itemDesc, true);
		$criteria->compare('weight', $this->weight, true);
		$criteria->compare('createDate', $this->createDate, true);
		$criteria->compare('modifiedDate', $this->modifiedDate, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}